name: Campsite Checker

on:
  schedule:
    - cron: '1 13-23 * * *'  # 1 min past each hour 6 AM to 4 PM MT
    - cron: '1 0-5 * * *'    # 1 min past each hour 5 PM to 10 PM MT
  workflow_dispatch:     # Manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the bot
      env:
        GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      run: python campsite_bot.py